# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'msgPush'

steps:
# - script: |
#     docker build -t $(dockerId)/$(imageName) .
#     docker login -u $(dockerId) -p $(dockerHubPwd)
#     docker push $(dockerId)/$(imageName)
#   displayName: 'docker image build and publish'

- task: SSH@0
  inputs:
    sshEndpoint: 'deployServer'
    runOptions: 'commands'
    commands: '
      cd ~/deploy &&
      export Jwt_SecretKey="$(Jwt_SecretKey)" &&
      docker-compose down &&
      docker-compose rm -f &&
      docker-compose up'