version: '3.1'

services:
  messagepush-server:
    image: jimchen8889/messagepush:latest
    restart: always
    ports:
      - 5000:80
    environment:
      - Jwt_SecretKey
      - Recaptcha_SecretKey
      - SecretKey
      - Db_ConnectionString
    depends_on:
      - rabbit-mq

  rabbit-mq:
    image: rabbitmq:3
    restart: always
    ports:
      - 5672:5672

  messagepush-mid:
    image: jimchen8889/msgpush-mid:latest
    restart: always
    environment:
      - Telegram_Token
    depends_on:
      - rabbit-mq
